config/routes.rb
Rails.application.routes.draw do
  resources :policies
  resources :indications
  resources :agencies
  resources :user_profiles
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/indication.rb
class Indication < ActiveRecord::Base
end

app/controllers/indications_controller.rb
class IndicationsController < ApplicationController
  before_action :set_indication, only: [:show, :edit, :update, :destroy]

  # GET /indications
  # GET /indications.json
  def index
    @indications = Indication.all
  end

  # GET /indications/1
  # GET /indications/1.json
  def show
  end

  # GET /indications/new
  def new
    @indication = Indication.new
  end

  # GET /indications/1/edit
  def edit
  end

  # POST /indications
  # POST /indications.json
  def create
    @indication = Indication.new(indication_params)

    respond_to do |format|
      if @indication.save
        format.html { redirect_to @indication, notice: 'Indication was successfully created.' }
        format.json { render :show, status: :created, location: @indication }
      else
        format.html { render :new }
        format.json { render json: @indication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indications/1
  # PATCH/PUT /indications/1.json
  def update
    respond_to do |format|
      if @indication.update(indication_params)
        format.html { redirect_to @indication, notice: 'Indication was successfully updated.' }
        format.json { render :show, status: :ok, location: @indication }
      else
        format.html { render :edit }
        format.json { render json: @indication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indications/1
  # DELETE /indications/1.json
  def destroy
    @indication.destroy
    respond_to do |format|
      format.html { redirect_to indications_url, notice: 'Indication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indication
      @indication = Indication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indication_params
      params.require(:indication).permit(:underwriter_id, :state, :effective_date, :expire_date, :wholesale_agency_id, :retail_agency_id, :placement_fee, :employee_payroll, :owner_payroll, :total_payroll, :sub_out_commercial, :sub_out_residential, :gross_receipts_current, :description_of_operations, :type_of_contractor, :type_al_requested, :limits_selected, :insured_ops, :limits, :rating_factor, :dba, :name, :zip, :address1, :address2, :city, :email, :fax, :phone, :state_code, :gf_comments, :approval_comments, :pdf_natural_url, :pdf_tracking_url, :mgu_id)
    end
end

app/helpers/indications_helper.rb
module IndicationsHelper
end

app/views/indications/_form.html.erb
<%= simple_form_for(@indication) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :underwriter_id %>
    <%= f.input :state %>
    <%= f.input :effective_date %>
    <%= f.input :expire_date %>
    <%= f.input :wholesale_agency_id %>
    <%= f.input :retail_agency_id %>
    <%= f.input :placement_fee %>
    <%= f.input :employee_payroll %>
    <%= f.input :owner_payroll %>
    <%= f.input :total_payroll %>
    <%= f.input :sub_out_commercial %>
    <%= f.input :sub_out_residential %>
    <%= f.input :gross_receipts_current %>
    <%= f.input :description_of_operations %>
    <%= f.input :type_of_contractor %>
    <%= f.input :type_al_requested %>
    <%= f.input :limits_selected %>
    <%= f.input :insured_ops %>
    <%= f.input :limits %>
    <%= f.input :rating_factor %>
    <%= f.input :dba %>
    <%= f.input :name %>
    <%= f.input :zip %>
    <%= f.input :address1 %>
    <%= f.input :address2 %>
    <%= f.input :city %>
    <%= f.input :email %>
    <%= f.input :fax %>
    <%= f.input :phone %>
    <%= f.input :state_code %>
    <%= f.input :gf_comments %>
    <%= f.input :approval_comments %>
    <%= f.input :pdf_natural_url %>
    <%= f.input :pdf_tracking_url %>
    <%= f.input :mgu_id %>
    <%= f.input :total_policy_cost %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/indications/edit.html.erb
<h1>Editing Indication</h1>

<%= render 'form' %>

<%= link_to 'Show', @indication %> |
<%= link_to 'Back', indications_path %>

app/views/indications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indications</h1>

<table>
  <thead>
    <tr>
      <!-- <th>Underwriter</th> -->
      <th>State</th>
      <th>Effective</th>
      <!-- <th>Expire date</th> -->
      <!-- <th>Wholesale agency</th> -->
      <th>Retail Brokerage</th>
      <!-- <th>Placement fee</th> -->
      <!-- <th>Employee payroll</th> -->
      <!-- <th>Owner payroll</th> -->
      <!-- <th>Total payroll</th> -->
      <!-- <th>Sub out commercial</th> -->
      <!-- <th>Sub out residential</th> -->
      <!-- <th>Gross receipts current</th> -->
      <!-- <th>Description of operations</th> -->
      <!-- <th>Type of contractor</th> -->
      <!-- <th>Type al requested</th> -->
      <!-- <th>Limits selected</th> -->
      <!-- <th>Insured ops</th> -->
      <!-- <th>Limits</th> -->
      <!-- <th>Rating factor</th> -->
      <th>Applicant Name</th>
      <th>Applicant DBA</th>
  <!--     <th>Zip</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>Email</th>
      <th>Fax</th>
      <th>Phone</th>
      <th>State code</th>
      <th>Gf comments</th>
      <th>Approval comments</th>
      <th>Pdf natural url</th>
      <th>Pdf tracking url</th>
      <th>Mgu</th> -->
      <th>Total Policy Cost</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indications.each do |indication| %>
      <tr>
        <!-- <td><%= indication.underwriter_id %></td> -->
        <td><%= indication.state %></td>
        <td><%= indication.effective_date %></td>
<!--         <td><%= indication.expire_date %></td>
        <td><%= indication.wholesale_agency_id %></td> -->
        <td><%= indication.retail_agency_id %></td>
        <!-- <td><%= indication.placement_fee %></td> -->
        <!-- <td><%= indication.employee_payroll %></td> -->
        <!-- <td><%= indication.owner_payroll %></td> -->
        <!-- <td><%= indication.total_payroll %></td> -->
        <!-- <td><%= indication.sub_out_commercial %></td> -->
        <!-- <td><%= indication.sub_out_residential %></td> -->
        <!-- <td><%= indication.gross_receipts_current %></td> -->
        <!-- <td><%= indication.description_of_operations %></td> -->
        <!-- <td><%= indication.type_of_contractor %></td> -->
        <!-- <td><%= indication.type_al_requested %></td> -->
        <!-- <td><%= indication.limits_selected %></td> -->
        <!-- <td><%= indication.insured_ops %></td> -->
        <!-- <td><%= indication.limits %></td> -->
        <!-- <td><%= indication.rating_factor %></td> -->
        <td><%= indication.name %></td>
        <td><%= indication.dba %></td>
        <!-- <td><%= indication.zip %></td> -->
        <!-- <td><%= indication.address1 %></td> -->
        <!-- <td><%= indication.address2 %></td> -->
        <!-- <td><%= indication.city %></td> -->
        <!-- <td><%= indication.email %></td> -->
        <!-- <td><%= indication.fax %></td> -->
        <!-- <td><%= indication.phone %></td> -->
        <!-- <td><%= indication.state_code %></td> -->
        <!-- <td><%= indication.gf_comments %></td> -->
        <!-- <td><%= indication.approval_comments %></td> -->
        <!-- <td><%= indication.pdf_natural_url %></td> -->
        <!-- <td><%= indication.pdf_tracking_url %></td> -->
        <!-- <td><%= indication.mgu_id %></td> -->
        <td><%= indication.total_policy_cost %></td>
        <td><%= link_to 'Show', indication %></td>
        <td><%= link_to 'Edit', edit_indication_path(indication) %></td>
        <td><%= link_to 'Destroy', indication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indication', new_indication_path %>

app/views/indications/new.html.erb
<h1>New Indication</h1>

<%= render 'form' %>

<%= link_to 'Back', indications_path %>

app/views/indications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Underwriter:</strong>
  <%= @indication.underwriter_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @indication.state %>
</p>

<p>
  <strong>Effective date:</strong>
  <%= @indication.effective_date %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @indication.expire_date %>
</p>

<p>
  <strong>Wholesale agency:</strong>
  <%= @indication.wholesale_agency_id %>
</p>

<p>
  <strong>Retail agency:</strong>
  <%= @indication.retail_agency_id %>
</p>

<p>
  <strong>Placement fee:</strong>
  <%= @indication.placement_fee %>
</p>

<p>
  <strong>Employee payroll:</strong>
  <%= @indication.employee_payroll %>
</p>

<p>
  <strong>Owner payroll:</strong>
  <%= @indication.owner_payroll %>
</p>

<p>
  <strong>Total payroll:</strong>
  <%= @indication.total_payroll %>
</p>

<p>
  <strong>Sub out commercial:</strong>
  <%= @indication.sub_out_commercial %>
</p>

<p>
  <strong>Sub out residential:</strong>
  <%= @indication.sub_out_residential %>
</p>

<p>
  <strong>Gross receipts current:</strong>
  <%= @indication.gross_receipts_current %>
</p>

<p>
  <strong>Description of operations:</strong>
  <%= @indication.description_of_operations %>
</p>

<p>
  <strong>Type of contractor:</strong>
  <%= @indication.type_of_contractor %>
</p>

<p>
  <strong>Type al requested:</strong>
  <%= @indication.type_al_requested %>
</p>

<p>
  <strong>Limits selected:</strong>
  <%= @indication.limits_selected %>
</p>

<p>
  <strong>Insured ops:</strong>
  <%= @indication.insured_ops %>
</p>

<p>
  <strong>Limits:</strong>
  <%= @indication.limits %>
</p>

<p>
  <strong>Rating factor:</strong>
  <%= @indication.rating_factor %>
</p>

<p>
  <strong>Dba:</strong>
  <%= @indication.dba %>
</p>

<p>
  <strong>Name:</strong>
  <%= @indication.name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @indication.zip %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @indication.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @indication.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @indication.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @indication.email %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @indication.fax %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @indication.phone %>
</p>

<p>
  <strong>State code:</strong>
  <%= @indication.state_code %>
</p>

<p>
  <strong>Gf comments:</strong>
  <%= @indication.gf_comments %>
</p>

<p>
  <strong>Approval comments:</strong>
  <%= @indication.approval_comments %>
</p>

<p>
  <strong>Pdf natural url:</strong>
  <%= @indication.pdf_natural_url %>
</p>

<p>
  <strong>Pdf tracking url:</strong>
  <%= @indication.pdf_tracking_url %>
</p>

<p>
  <strong>Mgu:</strong>
  <%= @indication.mgu_id %>
</p>

<%= link_to 'Edit', edit_indication_path(@indication) %> |
<%= link_to 'Back', indications_path %>