config/routes.rb
Rails.application.routes.draw do
  resources :policies
  resources :indications
  resources :agencies
  resources :user_profiles
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/agency.rb
class Agency < ActiveRecord::Base
  validates_inclusion_of :type_of, :in => ['retail', 'wholesale', 'mgu']
  validates_presence_of :name
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:id, :type_of, :name, :dba, :display_name, :address1, :address2, :zip, :email, :phone, :fax)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= content_tag(:br) %>
<%= simple_form_for(@agency) do |f| %>
  <fieldset>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="form-group">
        <%= f.label :type_of, 'type of agency' %>
        <%= f.select :type_of, ['retail','wholesale','mgu'], {:include_blank => true}, {class: 'form-control floating-label', placeholder: 'type', disabled: false} %>
      </div>
      <%= f.input :name %>
      <%= f.input :dba %>
      <%= f.input :display_name %>
      <%= f.input :address1 %>
      <%= f.input :address2 %>
      <%= f.input :zip %>
      <%= f.input :email %>
      <%= f.input :phone %>
      <%= f.input :fax %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </fieldset>

<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>
<section id="content">
  <div class="container">
    <div class="card">
      <div class="card-header">
          <h3>Work with Agencies</h3>
      </div>

      </br>

      <!-- Top Search Content -->
      <div id="top-search-wrap">
          <div class="tsw-inner">
              <i id="top-search-close" class="zmdi zmdi-arrow-left"></i>
              <input type="text", placeholder="Search Agencies">
          </div>
      </div>

      </br>

      <div class="table-responsive">
          <table id="data-table-basic" class="table table-striped">
              <thead>
                  <tr>
                      <th data-column-id="agencyName">Agency Name</th>
                  </tr>
              </thead>
              <tbody>
                <% @agencies.each do |agency| %>
                  <tr>
                    <td><%= agency.name %></td>
                    <td><%= link_to 'Show', agency %></td>
                    <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
                    <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        <br>
        <%= link_to 'New Agency', new_agency_path %>
      </div>
    </div>

    <ul class="pagination lv-pagination">
        <li>
            <a href="" aria-label="Previous">
                <i class="zmdi zmdi-chevron-left"></i>
            </a>
        </li>
        <li class="active"><a href="">1</a></li>
        <li><a href="">2</a></li>
        <li><a href="">3</a></li>
        <li><a href="">4</a></li>
        <li><a href="">5</a></li>
        <li>
            <a href="" aria-label="Next">
                <i class="zmdi zmdi-chevron-right"></i>
            </a>
        </li>
    </ul>

  </div>


</section>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form' %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @agency.id %>
</p>

<p>
  <strong>Type of:</strong>
  <%= @agency.type_of %>
</p>

<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Dba:</strong>
  <%= @agency.dba %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @agency.display_name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @agency.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @agency.address2 %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @agency.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agency.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agency.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @agency.fax %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>