config/routes.rb
Rails.application.routes.draw do
  resources :policies
  resources :indications
  resources :agencies
  resources :user_profiles
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base

# VALIDATIONS (Start) ===================================================================
  validates    :user_id,                                  :presence    => true
# VALIDATIONS (End)

# DEFAULTS (Start) ======================================================================

# DEFAULTS (End)

# ASSOCIATIONS (Start) ==================================================================
  belongs_to   :user
# ASSOCIATIONS (End)

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
    @user_profile = current_user.user_profile
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
    @user = current_user
    @user_profile = @user.user_profile
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    @user_profile = current_user.user_profile
    if params[:user_profile][:picture] != nil
      uploaded_io = params[:user_profile][:picture]
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
      end
    end
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find_by_user_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :first_name, :last_name, :phone_number, :facebook_user, :twitter_handle, :address_1, :address_2, :city, :state, :postal_code, :mobile_number)
    end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= simple_form_for(@user_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone_number %>
    <%= f.input :facebook_user %>
    <%= f.input :twitter_handle %>
    <%= f.input :address_1 %>
    <%= f.input :address_2 %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :postal_code %>
    <%= f.input :mobile_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<!--
<div class="authform">
<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>
</div>
-->
<div class="authform">
<h3>Edit User Profile</h3>
  <%= form_for(@user.user_profile, html: { method: :patch }) do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>

    <fieldset>
      <p>Change your contact information here.</p>

      <div class="form-group">
        <%= f.label :address_1, "Address" %>
        <%= f.text_field :address_1, class: 'form_control' %>
        <%= f.text_field :address_2, class: 'form_control' %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city, class: 'form_control' %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state, maxlength: 2, class: 'form_control' %>
        <%= f.label :postal_code, "Zip" %>
        <%= f.text_field :postal_code, maxlength: 9, class: 'form_control' %>
      </div>
      <div class="form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :mobile_number %>
        <%= f.text_field :mobile_number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :facebook_user %>
        <%= f.text_field :facebook_user, class: 'form-control' %>
      </div>
            <div class="form-group">
        <%= f.label :twitter_handle %>
        <%= f.text_field :twitter_handle, class: 'form-control' %>
      </div>
    </fieldset>

    <fieldset>
      <div class="form-group">
        <%= f.label :profile_picture %>
        <%= f.file_field :picture %>
      </div>
    </fieldset>
    <%= f.submit 'Update', :class => 'button right' %>
  <h3><%= link_to 'edit account', edit_user_registration_path %></h3>
  <% end %>
</div>

app/views/user_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Facebook user</th>
      <th>Twitter handle</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Mobile number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.user_id %></td>
        <td><%= user_profile.first_name %></td>
        <td><%= user_profile.last_name %></td>
        <td><%= user_profile.phone_number %></td>
        <td><%= user_profile.facebook_user %></td>
        <td><%= user_profile.twitter_handle %></td>
        <td><%= user_profile.address_1 %></td>
        <td><%= user_profile.address_2 %></td>
        <td><%= user_profile.city %></td>
        <td><%= user_profile.state %></td>
        <td><%= user_profile.postal_code %></td>
        <td><%= user_profile.mobile_number %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New User Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_profile.user_id %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user_profile.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_profile.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user_profile.phone_number %>
</p>

<p>
  <strong>Facebook user:</strong>
  <%= @user_profile.facebook_user %>
</p>

<p>
  <strong>Twitter handle:</strong>
  <%= @user_profile.twitter_handle %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @user_profile.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @user_profile.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @user_profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user_profile.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @user_profile.postal_code %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @user_profile.mobile_number %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>